# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mw3OLoYytYeGhNNR1BuGAFXvnWEtYiWA
"""

import pandas as pd
import numpy as np
import datetime as dt
from sklearn.preprocessing import MinMaxScaler
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
global dfc
dfc = pd.read_excel (r'drive/MyDrive/colab files/complete_site_info.xlsx')

dfc5=dfc.copy()
dfc5=dfc5.groupby('Site_Name').mean()
dfc7=dfc5[['Tourists_Count','Temperature','Israelis_Count','Total','pm10','pm2.5','nox','so2']]
dfc5=dfc5[['camping', 'special_activity','visit_duration','jewish','muslims','christians','national park',\
            'nature reserve','archaeology','religion','animals','heritage','water','cave','lookout','region_Central','region_Judea_Samaria','region_North','region_South','Tourists_Count','Temperature','Israelis_Count','Total','pm10','pm2.5','nox','so2',]]

def choice(arr):
  global dfc
  dfc=dfc[arr]
  dfc = dfc.drop_duplicates(subset=["Site_Name"])
  dfc.dropna(inplace=True)
  dfc = pd.DataFrame(dfc).set_index('Site_Name')
  dfc = pd.concat([dfc,dfc7 ], axis=1, join="inner")
  print(dfc.head())
choice(['Site_Name','camping', 'special_activity','visit_duration','jewish','muslims','christians','national park',\
            'nature reserve','archaeology','religion','animals','heritage','water','cave','lookout','region_Central','region_Judea_Samaria','region_North','region_South'])

global scaled_dfc
def ClusterScale():
  global scalerc
  global scaled_dfc
  scalerc = StandardScaler()
  scalerc.fit(dfc)
  scaled_dfc = pd.DataFrame(scalerc.transform(dfc), columns=dfc.columns)
ClusterScale()

#Elbow Test, choosing the best value visually, based on where the value drops less.
from logging import warning
from sklearn.cluster import KMeans
def ElbowTest():
  global sse
  sse = []
  k=1
  while 1:
    km = KMeans(n_clusters=k)
    km.fit(scaled_dfc)
    if(km.inertia_==0):
      break
    k+=1

    sse.append(km.inertia_)

  fig = go.Figure()
  fig.add_trace(go.Scatter( y=sse, mode='markers+lines'))
  fig.update_layout(
      title="Inertia by K",
      xaxis_title="K",
      yaxis_title="Inertia",
      font=dict(
          family="Courier New, monospace",
          size=14,
          color="RebeccaPurple"
      ),
      width=800
  )

  fig.show()
ElbowTest()

#Closer to 1 --> the clusers are further apart
from sklearn.metrics import silhouette_score
def SillTest():
  global sil
  sil = []
  k=2
  kmeans = KMeans(n_clusters=len(dfc.columns)).fit(scaled_dfc)
  labels = kmeans.labels_
  score3=silhouette_score(scaled_dfc, labels, metric = 'euclidean')
  score2=score3


  for i in range(0, len(dfc.columns)) :
    kmeans = KMeans(n_clusters=k).fit(scaled_dfc)
    labels = kmeans.labels_
    score1=silhouette_score(scaled_dfc, labels, metric = 'euclidean')

    if score1==score2 and score1==score3:
      break
    k+=1
    sil.append(score1)
    score2=sil[-1]
    if k>=4:
     score3=sil[-2]
  fig = go.Figure()
  fig.add_trace(go.Scatter(y=sil, mode='markers+lines'))
  fig.update_layout(
      title="Inertia by K",
      xaxis_title="K",
      yaxis_title="Inertia",

      font=dict(
          family="Courier New, monospace",
          size=14,
          color="RebeccaPurple"
      ),
      width=800
  )

  fig.show()
SillTest()

global Clusters_List
global labels
global cluster_means
global K_means
K_means=15
def Cluster():
  global K_means
  global cluster_means
  global Clusters_List
  kmeans = KMeans(n_clusters=K_means, random_state=1234)
  kmeans.fit_predict(scaled_dfc)
  kmeans.cluster_centers_
  global labels
  labels = kmeans.labels_
  dfc['cluster'] = labels
  cluster_means = dfc.groupby('cluster').mean()
  cluster_centers = scalerc.inverse_transform(kmeans.cluster_centers_)
  dfcc=dfc.copy()
  dfcc['SiteName'] = dfc.index
  dfcc = dfcc.rename_axis('index1').reset_index()

  dfcc = pd.crosstab([dfcc.cluster, dfcc.SiteName], 0, margins=True)
  i=0

  Cluster_List=[]
  Clusters_List=[]
  for index, row in dfcc.iterrows():
    if index[0] is not 'All':
      if float(index[0])>i:
        i+=1
        Clusters_List.append(Cluster_List)
        Cluster_List=[]
      Cluster_List.append(index[1])

  Clusters_List.append(Cluster_List)
  return Clusters_List

#Clustering Loss Function by: sum[K](sum[i](Avr[i]-X[i])^2)
def Cluster_LossFunction():
  global K_means
  global cluster_means
  SumK=0
  SumI=0

  for k in range(0,K_means):
    if k!=0:
      SumK+=(SumI)

    for i in range(0,len(Clusters_List[k])):
      for j in range(0,len(dfc5.columns)):
        #mean is in df5, overall cluser mean in cluster_means
        SumI=pow(dfc5.loc[Clusters_List[k][i]][j]-cluster_means.iloc[k][j],2)
  print(SumK)

#More details for the clustering made
def Print_Clusters_Details():
  global Clusters_List
  global cluster_means
  global labels
  count=dfc['cluster'].value_counts()
  cluster_stds = dfc.groupby('cluster').std()

  print("----------------Sites Clustered---------------- \n")
  for i in Clusters_List:
    print(i)
  print("----------------Cluster labels---------------- \n",labels)
  print("----------------Cluster Count---------------- \n",count)
  print("----------------Cluster Means---------------- \n",cluster_means)
  print("----------------Cluster STD---------------- \n",cluster_stds)

class bcolors:
    GREEN = '\033[92m' #GREEN
    YELLOW = '\033[93m' #YELLOW
    RED = '\033[91m' #RED
    RESET = '\033[0m' #RESET COLOR

def FindCluster(Name):
  global Clusters_List
  loc=0
  check=0
  arr=[]
  for i in range(0,len(Clusters_List)) :
    for j in range(0,len(Clusters_List[i])):
      if Clusters_List[i][j]==Name:
        check=1
        loc=i
  for i in range(0,len(Clusters_List[loc])):
    if Clusters_List[loc][i]!=Name:
      arr.append(Clusters_List[loc][i])
  if check==1 and len(arr)>0:
    return arr
  return False
def Print_Cluster_Info(arr,Name):
  name_df=dfc.loc[Name]
  print("--------------Our Recommendations:--------------\n")
  print("------------Here are other sites you might be interested in! (Similar attributes are marked)------------\n")
  for item in arr:
    if item!=Name:
      print("\nSite Name: ",item )
      Group_Item_df=dfc.loc[item]
      for column in dfc.columns:
        if (name_df[column]==Group_Item_df[column] and Group_Item_df[column]==1) or ((column=='Tourists_Count' or column=='Temperature' or column=='Israelis_Count' or column=='Total') and (abs(name_df[column]-Group_Item_df[column]<20)) and column !='cluster' )   :
          print(bcolors.GREEN," ",column,": ", Group_Item_df[column], bcolors.RESET,end='')

  print("----------------------------------------------------------------------\n")
def Site_Info(Name):
  name_df=dfc.loc[Name]
  print("--------------Site Info: (Averages)--------------")
  print(bcolors.GREEN,"Site Name: ",Name,bcolors.RESET)
  count=0
  for column in dfc.columns:
    count+=1
    if column !='cluster':
      print(" ",column,": ", name_df[column],end='')
    if count == 4:
      count=0
      print("")
  print("----------------------------------------------------------------------\n")

Print_Cluster_Info(FindCluster('Arbel'),'Arbel')