# -*- coding: utf-8 -*-
"""Data Analysis Mobile Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNmADeqq_rJ4jyVj4S-Rk1sdZHDfnFlN
"""

!pip install PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

file_id = '1swgtgBxRf_1QN_hcZA8CCTbVKpmC974W'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('data.csv')

import pandas as pd

df = pd.read_csv('data.csv')

df.head()

# Question 1:

import pandas as pd

def top_urls_by_pageviews(device_type, geo_location, df):
    # Filter data by device type and geo location
    filtered_df = df[(df['device_type'] == device_type) & (df['geo_location'] == geo_location)]

    # Group by URL and calculate total pageviews
    url_pageviews = filtered_df.groupby('URL')['pageviews'].sum().reset_index()

    # Sort URLs by pageviews in descending order
    url_pageviews_sorted = url_pageviews.sort_values(by='pageviews', ascending=False)

    # Get top 3 URLs
    top_urls = url_pageviews_sorted.head(3)

    return top_urls

device_type = 'MOBILE'
geo_location = 'us'

top_urls = top_urls_by_pageviews(device_type, geo_location, df)
print("Top URLs by pageviews:")
print(top_urls)

df.head()

#Explaination: group by seemed to be the perfect approach here, followed by a sort and print as requested. My assumptions are that the data frame is not empty and we have already examined it.

!pip install matplotlib seaborn pandas

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Bar plot - Total pageviews for each geo and device type
plt.figure(figsize=(10, 6))
sns.barplot(x='geo_location', y='pageviews', hue='device_type', data=df, estimator=sum, ci=None)
plt.title('Total Pageviews by Geo and Device Type')
plt.xlabel('Geo Location')
plt.ylabel('Total Pageviews')
plt.legend(title='Device Type')
plt.show()

# Heatmap - Pageviews across different geos and devices
heatmap_data = df.pivot_table(index='geo_location', columns='device_type', values='pageviews', aggfunc=sum)
plt.figure(figsize=(8, 6))
sns.heatmap(heatmap_data, annot=True, cmap='YlGnBu', fmt='g')
plt.title('Pageviews across Geos and Devices')
plt.xlabel('Device Type')
plt.ylabel('Geo Location')
plt.show()

df.head()

import pandas as pd

# Assuming df is your existing DataFrame with columns: viewed_impressions, impressions

def calculate_viewability_tier(row):
    if row['impressions'] == 0:
        return 'Invalid'
    viewability = row['viewed_impressions'] / row['impressions']
    if viewability < 0.35:
        return 'Low Viewability'
    elif 0.35 <= viewability <= 0.65:
        return 'Medium Viewability'
    elif viewability > 0.65:
        return 'High Viewability'
    else:
        return 'Invalid'

# Add viewability tier column to df
df['viewability_tier'] = df.apply(calculate_viewability_tier, axis=1)

# Display the updated DataFrame with viewability tier
print(df.head())

# Count the number of occurrences of each viewability tier
tier_counts = df['viewability_tier'].value_counts()

# Calculate percentages of total
total_entries = len(df)
tier_percentages = (tier_counts / total_entries) * 100

# Plotting the distribution with percentages
plt.figure(figsize=(10, 6))
ax = sns.countplot(x='viewability_tier', data=df, palette='viridis')
plt.title('Distribution of Viewability Tiers', fontsize=16, fontweight='bold')
plt.xlabel('Viewability Tier', fontsize=14)
plt.ylabel('Count', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)
plt.yticks(fontsize=12)

# Add percentages on top of each bar
for p, percentage in zip(ax.patches, tier_percentages):
    height = p.get_height()
    ax.text(p.get_x() + p.get_width() / 2.,
            height + 0.5,
            f'{percentage:.1f}%',
            ha='center', va='bottom', fontsize=10, color='black')

plt.tight_layout()
plt.show()