# -*- coding: utf-8 -*-
"""Locals vs tourists(Wilcoxon).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qYW_97ZOI76oYkO1A5yGwI3JE9PLbOkc
"""

import pandas as pd

df1 = pd.read_excel (r'drive/MyDrive/colab files/complete_site_info.xlsx')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

def ecdf(data):
    n = len(data)
    x = np.sort(data)
    y = np.arange(1, n+1) / n
    return x, y

df1.head()

x, y = ecdf(df1["Israelis_Count"])

plt.figure(figsize=(8,7))
sns.set()
plt.plot(x, y, marker=".", linestyle="none")
plt.xlabel("Body Temperature (F)")
plt.ylabel("Cumulative Distribution Function")

samples = np.random.normal(np.mean(df1["Israelis_Count"]), np.std(df1["Israelis_Count"]), size=10000)

x_theor, y_theor = ecdf(samples)

plt.plot(x_theor, y_theor)
plt.legend(('Normal Distribution', 'Empirical Data'), loc='lower right')
#periscope.output(plt)

stat,pvalue=stats.normaltest(df1["Israelis_Count"])
if pvalue<0.05:
  print("not normal distribution\n","stat:",stat,"pvalue:",pvalue)
else:
   print("normal distribution\n","stat:",stat,"pvalue:",pvalue )

stat,pvalue=stats.normaltest(df1["Tourists_Count"])
if pvalue<0.05:
  print("not normal distribution\n","stat:",stat,"pvalue:",pvalue)
else:
   print("normal distribution\n","stat:",stat,"pvalue:",pvalue )

from scipy.stats import wilcoxon
from numpy import mean
from numpy import std
data1=df1["Tourists_Count"]
data2=df1["Israelis_Count"]
stat, p = wilcoxon(data1, data2)
print('Statistics=%.3f, p=%.3f' % (stat, p))
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

print('Tourists: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('Israelis: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))