# -*- coding: utf-8 -*-
"""nltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EehMmb5svDx9HjkgrgfACn5cL28PIAfl
"""

from google.colab import files #upload
import nltk
nltk.download('punkt')
uploaded = files.upload()

#File entered to readable lines
l=list(uploaded.keys())[0]
import re
File=re.split('\n',uploaded[l].decode("utf-8"))
for i in range(len(File)):
  File[i]=File[i].rstrip()

#lines to list
global lines
lines=[]
for item in File:
    lines.append(item)

print(lines[0:10])

#Tokenizing
NewList=[]
for item in lines:
  tokens = nltk.word_tokenize(item)
  NewList.append(tokens)
print(NewList)

#splitting
import pandas as pd
from sklearn.model_selection import train_test_split
data = pd.DataFrame(NewList)


data=data.iloc[:, 0: 5]
data.rename(columns = {0:'W1', 1:'W2',2:'W3',3:'W4',4:'True Value'}, inplace = True)
data.drop(data[data['W4'].isnull()].index, inplace = True)
data=data.iloc[0:1500,:]
print(data)


X=data.iloc[:, 0: 4]
y=data.iloc[:, 4: 5]

X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1357)
train_df = pd.merge(left=X_train, right=y_train, left_index=True, right_index=True)
test_df = pd.merge(left=X_test, right=y_test, left_index=True, right_index=True)
train_df

#  θ(N/3*N/7)=N^2. Long run time on colab on original file. sample reduced to 1500 rows.
def Calc(count, V): # calculating P(V|number exist)
  if V==0 and count ==0:
    return 1
  if V/(count)>0.5:
    return 'V'
  return 'N'

def CountExist(row,train_df): # For each row in test sample, check for each row in the train test. For example, if 4 exist return count of 4 in the train test and the count V's of 4 for prediction. The same for 1,2,3 and 0.
  count1=0
  count2=0
  count3=0
  count4=0
  V1=0
  V2=0
  V3=0
  V4=0
  maxx=0
  arr=[row['W1'],row['W2'],row['W3'],row['W4']]

  for index,TrainRow in train_df.iterrows():
    if(arr[2]==TrainRow['W3']):
      if(TrainRow['True Value']=='V'):
            V1+=1
      count=1
      for i in range(0,len(arr)):

        if ((i is not 2) and (arr[i] == TrainRow.iloc[i])) and count==1:
          count=2
          if(TrainRow['True Value']=='V'):
            V2+=1
          continue

        if ((i is not 2) and (arr[i] == TrainRow.iloc[i])) and count==2 :
          count=3
          if(TrainRow['True Value']=='V'):
            V3+=1
          continue
        if ((i is not 2) and (arr[i] == TrainRow.iloc[i])) and count==3:
          if(TrainRow['True Value']=='V'):
            V4+=1
          count=4

      if count==4:
        count4+=1
      if count==3:
        count3+=1
      if count==2:
        count2+=1
      if count==1:
        count1+=1

  maxV=0
  maxCount=0

  if count1>0:
    maxV=V1
    maxCount=count1

  if count2>0:
    maxV=V2
    maxCount=count2

  if count3>0:
    maxV=V3
    maxCount=count3

  if count4>0:
    maxV=V4
    maxCount=count4

  return Calc(maxCount,maxV)

test_df['Predict']=test_df.apply (lambda row: CountExist(row,train_df), axis=1)

test_df

#results
Total=0
Right=0
for index,TrainRow in test_df.iterrows():
  Total+=1
  if TrainRow['True Value']==TrainRow['Predict']:
    Right+=1
print("Total Tested: ",Total, "\nRight Predictions: ", Right)
print("Prediction Accuracy: ", Right/Total)