# -*- coding: utf-8 -*-
"""NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ouJCybpCqGNgCCkYsFvNPMmpECgdyKq
"""

import pandas as pd
import numpy as np
import datetime as dt
from sklearn.preprocessing import MinMaxScaler
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
global dfn
dfn = pd.read_excel (r'drive/MyDrive/colab files/complete_site_info.xlsx')

def SiteEx(SiteName,b,pred):
  global dfn2, predict
  predict=pred
  dfn2=dfn.copy()
  dfn2=dfn2.loc[dfn2['Site_Name']==SiteName]
  if b== True:
    dfn2=dfn2[[pred,'Temperature','is_HeatWave','is_weekend','pm2.5','nox','so2','pm10']]
  else:
    dfn2=dfn2[['Temperature',pred,'is_HeatWave','is_weekend']]
SiteEx('Arbel',False,'Israelis_Count')

dfn2

def XnY():
  global y
  y=dfn2[predict]
  global X
  X=dfn2.drop(columns=[predict],axis=1)
XnY()

def split():
  global X_train,X_test,y_train,y_test,train_df,test_df
  X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1357)
  train_df = pd.merge(left=X_train, right=y_train, left_index=True, right_index=True)
  test_df = pd.merge(left=X_test, right=y_test, left_index=True, right_index=True)
split()

def scale():
  global x_train_scaler, x_test_scaler,y_train_scaler,y_test_scaler,X_train_scaled,X_test_scaled,y_train_scaled,y_test_scaled

  x_train_scaler = StandardScaler()
  x_test_scaler = StandardScaler()
  y_train_scaler = StandardScaler()
  y_test_scaler = StandardScaler()

  X_train_scaled = x_train_scaler.fit_transform(X_train)
  X_test_scaled = x_test_scaler.fit_transform(X_test)
  y_train_scaled = y_train_scaler.fit_transform(pd.DataFrame(y_train))
  y_test_scaled = y_test_scaler.fit_transform(pd.DataFrame(y_test))
scale()

import keras
keras.__version__
from keras import models
from keras import layers

def build_model():
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu',
                           input_shape=(X_train_scaled.shape[1],)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(1))
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
    return model

# #NN on Train Data set, MSE as loss function, MAE as Epochs Metric

# import numpy as np


# num_epochs = 25
# all_scores = []


# # Prepare the validation data: data from partition # k
# val_data = X_train_scaled[0: num_val_samples:]
# val_targets = y_train_scaled[0:  num_val_samples]

# # Prepare the training data: data from all other partitions
# partial_train_data = X_train_scaled[num_val_samples:]
# partial_train_targets = y_train_scaled[num_val_samples:]

# # Build the Keras model (already compiled)
# model = build_model()
# # Train the model (in silent mode, verbose=0)
# model.fit(partial_train_data, partial_train_targets,
#           epochs=num_epochs, batch_size=1, verbose=0)
# # Evaluate the model on the validation data
# val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
# all_scores.append(val_mae)

# print(all_scores)
# print(np.mean(all_scores))

#NN on Train Data set With validation, MSE as loss function, MAE as Epochs Metric

from keras import backend as K


K.clear_session()
num_val_samples = len(X_train_scaled) // 4
num_epochs = 100
all_mae_histories = []


val_data = X_train_scaled[0: num_val_samples]
val_targets = y_train_scaled[0: num_val_samples]


partial_train_data = np.concatenate(
    [X_train_scaled[:0],
      X_train_scaled[num_val_samples:]],
    axis=0)
partial_train_targets = np.concatenate(
    [y_train_scaled[:0],
      y_train_scaled[num_val_samples:]],
    axis=0)


model = build_model()

history = model.fit(partial_train_data, partial_train_targets,
                    validation_data=(val_data, val_targets),
                    epochs=num_epochs, batch_size=1, verbose=0)
mae_history = history.history['val_mae']

import matplotlib.pyplot as plt

plt.plot(range(1, len(mae_history) + 1), mae_history)
plt.xlabel('Epochs')
plt.ylabel('Validation MAE')
plt.show()

import matplotlib.pyplot as plt
history_dict = history.history
loss_values = history_dict["mae"]
val_loss_values = history_dict["val_mae"]
epochs = range(1, len(loss_values) + 1)
plt.plot(epochs, loss_values, "bo", label="Training mae")
plt.plot(epochs, val_loss_values, "b", label="Validation mae")
plt.title("Training and validation mae")
plt.xlabel("Epochs")
plt.ylabel("mae")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
history_dict = history.history
loss_values = history_dict["loss"]
val_loss_values = history_dict["val_loss"]
epochs = range(1, len(loss_values) + 1)
plt.plot(epochs, loss_values, "bo", label="Training loss")
plt.plot(epochs, val_loss_values, "b", label="Validation loss")
plt.title("Training and validation loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

import sys
import os

old_stdout = sys.stdout # backup current stdout
sys.stdout = open(os.devnull, "w")

model = build_model()

model.fit(X_train_scaled, y_train_scaled, epochs=80, batch_size=512)
Test_Mse,Test_Mae = model.evaluate(X_test_scaled, y_test_scaled)


sys.stdout = old_stdout # reset old stdout
print("MSE: ",Test_Mae,"\nMAE: ",Test_Mse)

def TestPredict():
  global test_df,predicted_test
  test_df.drop(columns=['Predicted_test_y','Predicted_test_x'],inplace=True)

  fitted_scaled = model.predict(X_test_scaled)
  fitted = y_test_scaler.inverse_transform(fitted_scaled)
  predicted_test = round(pd.Series(fitted[:,0], index=y_test.index, name='Predicted_test'),ndigits=2)
  test_df = pd.merge(left=test_df, right=predicted_test, left_index=True, right_index=True)
  print("\n-----------------TEST MODEL-----------------\n")
  print(test_df.head(20))
TestPredict()